In [ ]:
import math
import pandas_datareader as web
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

In [ ]:
df = pd.read_csv('gas_concentration.csv', parse_dates=['Date'],index_col='Date')

In [ ]:
CO2=df.filter(['CO2'])


In [ ]:
CO2_dataset=CO2.values

In [ ]:
training_len=math.ceil(len(CO2_dataset)*.8)
training_len

2957

In [ ]:
scaler_CO2=MinMaxScaler(feature_range=(0,1))
scaler_data_CO2=scaler_CO2.fit_transform(CO2_dataset)
scaler_data_CO2

array([[0.2027027 ],
       [0.19594595],
       [0.2027027 ],
       ...,
       [0.30405405],
       [0.30405405],
       [0.30405405]])

In [ ]:
training_data_CO2=scaler_data_CO2[0:training_len,:]
x_train_CO2=[]
y_train_CO2=[]
for i in range(60, len(training_data_CO2)):
    x_train_CO2.append(training_data_CO2[i-60:i,0])
    y_train_CO2.append(training_data_CO2[i,0])
    if i<= 60:
        print(x_train_CO2)
        print(y_train_CO2)

[array([0.2027027 , 0.19594595, 0.2027027 , 0.18918919, 0.19594595,
       0.18243243, 0.18243243, 0.18918919, 0.18918919, 0.19594595,
       0.2027027 , 0.2027027 , 0.18243243, 0.18243243, 0.18243243,
       0.17567568, 0.16891892, 0.16891892, 0.16891892, 0.16216216,
       0.16216216, 0.16891892, 0.16891892, 0.16891892, 0.16891892,
       0.16216216, 0.15540541, 0.15540541, 0.14189189, 0.14189189,
       0.13513514, 0.14864865, 0.14189189, 0.14864865, 0.14864865,
       0.14189189, 0.13513514, 0.13513514, 0.12837838, 0.12837838,
       0.12837838, 0.12162162, 0.12162162, 0.11486486, 0.11486486,
       0.10810811, 0.11486486, 0.11486486, 0.12837838, 0.15540541,
       0.16891892, 0.17567568, 0.17567568, 0.18243243, 0.2027027 ,
       0.22297297, 0.24324324, 0.25      , 0.27702703, 0.30405405])]
[0.3378378378378377]


In [ ]:
x_train_CO2,y_train_CO2=np.array(x_train_CO2),np.array(y_train_CO2)

In [ ]:
x_train_CO2=np.reshape(x_train_CO2,[x_train_CO2.shape[0],x_train_CO2.shape[1],1])
x_train_CO2.shape

(2897, 60, 1)

In [ ]:
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(x_train_CO2.shape[1],1)))
model.add(LSTM(50,return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

In [ ]:
model.compile(optimizer='Adam',loss='mean_squared_error')

In [ ]:
test_data_CO2 = scaler_data_CO2[training_len-60:,:]
x_test_CO2=[]
y_test_CO2=CO2_dataset[training_len:,:]
for i in range(60,len(test_data_CO2)):
    x_test_CO2.append(test_data_CO2[i-60:i,0])

In [ ]:
x_test_CO2=np.array(x_test_CO2)

In [ ]:
x_test_CO2=np.reshape(x_test_CO2,(x_test_CO2.shape[0],x_test_CO2.shape[1],1))

In [ ]:
y_test_CO2=scaler_CO2.fit_transform(y_test_CO2)
y_test_CO2

array([[0.   ],
       [0.   ],
       [0.   ],
       [0.   ],
       [0.   ],
       [0.   ],
       [0.   ],
       [0.   ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.05 ],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.075],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.1  ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.15 ],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.175],
       [0.2  ],
       [

In [ ]:
history_CO2 = model.fit(x_train_CO2, y_train_CO2, batch_size=70,epochs=300, validation_data=(x_test_CO2, y_test_CO2), shuffle=False)


Train on 2897 samples, validate on 739 samples
Epoch 1/300
2897/2897 [==============================] - 20s 7ms/step - loss: 0.0314 - val_loss: 0.0708
Epoch 2/300
2897/2897 [==============================] - 16s 5ms/step - loss: 0.0019 - val_loss: 0.1288
Epoch 3/300
2897/2897 [==============================] - 16s 5ms/step - loss: 0.0043 - val_loss: 0.0822
Epoch 4/300
2897/2897 [==============================] - 16s 6ms/step - loss: 0.0036 - val_loss: 0.1551
Epoch 5/300
2897/2897 [==============================] - 16s 6ms/step - loss: 0.0149 - val_loss: 0.0786
Epoch 6/300
2897/2897 [==============================] - 16s 5ms/step - loss: 0.0028 - val_loss: 0.1448
Epoch 7/300
2897/2897 [==============================] - 16s 6ms/step - loss: 0.0127 - val_loss: 0.0718
Epoch 8/300
2897/2897 [==============================] - 16s 6ms/step - loss: 0.0031 - val_loss: 0.1427
Epoch 9/300
2897/2897 [==============================] - 16s 5ms/step - loss: 0.0109 - val_loss: 0.0752
Epoch 10/300
289

2897/2897 [==============================] - 16s 5ms/step - loss: 3.7535e-04 - val_loss: 0.1086
Epoch 153/300
2897/2897 [==============================] - 16s 5ms/step - loss: 5.4926e-04 - val_loss: 0.0836
Epoch 154/300
2897/2897 [==============================] - 15s 5ms/step - loss: 4.5431e-04 - val_loss: 0.1104
Epoch 155/300
2897/2897 [==============================] - 16s 5ms/step - loss: 6.8804e-04 - val_loss: 0.0808
Epoch 156/300
2897/2897 [==============================] - 15s 5ms/step - loss: 5.9905e-04 - val_loss: 0.1128
Epoch 157/300
2897/2897 [==============================] - 16s 5ms/step - loss: 8.8833e-04 - val_loss: 0.0774
Epoch 158/300
2897/2897 [==============================] - 16s 5ms/step - loss: 7.1825e-04 - val_loss: 0.1137
Epoch 159/300
2897/2897 [==============================] - 16s 5ms/step - loss: 8.3601e-04 - val_loss: 0.0773
Epoch 160/300
2897/2897 [==============================] - 15s 5ms/step - loss: 5.6299e-04 - val_loss: 0.1095
Epoch 161/300
2897/2897 

2897/2897 [==============================] - 15s 5ms/step - loss: 3.1898e-04 - val_loss: 0.1064


In [ ]:
predictions_CO2=model.predict(x_test_CO2)
predictions_CO2=scaler_CO2.inverse_transform(predictions_CO2)

In [ ]:
y_test_CO2=scaler_CO2.inverse_transform(y_test_CO2)
y_test_CO2

array([[12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.5],
       [13.5],
       [13.5],
       [13.5],
       [13.5],
       [13

In [ ]:
rmse=np.sqrt(np.mean(predictions_CO2-y_test_CO2)**2)
rmse

1.073649869978186

In [ ]:
valid_CO2=CO2[training_len:]
valid_CO2['predictions_CO2']=predictions_CO2

/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
valid_CO2

CO2  predictions_CO2
Date                                      
2020-01-13 05:05:00  12.7        13.082949
2020-01-13 06:05:00  12.7        13.083253
2020-01-13 07:05:00  12.7        13.083398
2020-01-13 08:05:00  12.7        13.083397
2020-01-13 09:05:00  12.7        13.083312
...                   ...              ...
2020-12-02 19:05:00  15.7        13.815966
2020-12-02 20:05:00  15.7        13.815441
2020-12-02 21:05:00  15.7        13.815023
2020-12-02 22:05:00  15.7        13.814732
2020-12-02 23:05:00  15.7        13.814559

[739 rows x 2 columns]

In [ ]:
valid_CO2.to_csv('CO2.csv')

In [ ]:
predictions_CO2=model.predict(x_test_CO2)
predictions_CO2=scaler_CO2.inverse_transform(predictions_CO2)

In [ ]:
y_test_CO2=scaler_CO2.inverse_transform(y_test_CO2)
y_test_CO2

array([[12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.7],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [12.9],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13. ],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.1],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.3],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.4],
       [13.5],
       [13.5],
       [13.5],
       [13.5],
       [13.5],
       [13

In [ ]:
rmse=np.sqrt(np.mean(predictions_CO2-y_test_CO2)**2)
rmse

0.9980975825989844